Repository sejong-algorithm/Algorithm, pull requests merged in 2019-08, with the labels that each got.

#46 4 week_code
  syli9526/BJ1260.cpp
  syli9526/BJ2589.cpp
Labels: AnswerNeeded

#44 add 1260
  README.md
  wjdgur778/JH_1260.cpp
  wjdgur778/JH_1725.cpp
  wjdgur778/JH_1918.cpp
  wjdgur778/JH_1966.cpp
  wjdgur778/JH_2164.cpp
  wjdgur778/JH_2304.cpp
  wjdgur778/JH_2589.cpp
  wjdgur778/JH_2841.cpp
  wjdgur778/JH_3078.cpp
  wjdgur778/JH_4963.cpp
  wjdgur778/JH_5430.cpp
  wjdgur778/NewBJ/NewBJ.sln
  wjdgur778/NewBJ/NewBJ.vcxproj
  wjdgur778/NewBJ/NewBJ.vcxproj.filters
  wjdgur778/NewBJ/NewBJ/JH_10026.cpp
  wjdgur778/NewBJ/NewBJ/JH_1051.cpp
  wjdgur778/NewBJ/NewBJ/JH_1107.cpp
  wjdgur778/NewBJ/NewBJ/JH_14717.cpp
  wjdgur778/NewBJ/NewBJ/JH_1541.cpp
  wjdgur778/NewBJ/NewBJ/JH_1707.cpp
  wjdgur778/NewBJ/NewBJ/JH_1946.cpp
  wjdgur778/NewBJ/NewBJ/JH_2875.cpp
  wjdgur778/NewBJ/NewBJ/JH_4179.cpp
  wjdgur778/NewBJ/NewBJ/NewBJ.vcxproj
  wjdgur778/NewBJ/NewBJ/NewBJ.vcxproj.filters
Labels: MergeNeeded

#45 4Week 코드
  README.md
  Zojae031/CodingTest/10026.cpp
  Zojae031/CodingTest/2589.cpp
  Zojae031/CodingTest/CodingTest.vcxproj
  Zojae031/CodingTest/CodingTest.vcxproj.filters
Labels: MergeNeeded

#47 취업스터디 2Week
  취업스터디/2Week.md
Labels: MergeNeeded

#48 4 week 코드 추가
  .DS_Store
  syli9526/.DS_Store
  syli9526/BJ4963.cpp
  syli9526/BJ7569.cpp
Labels: ReviewNeeded

#49 add 7569
  README.md
  wjdgur778/JH_7569.cpp
Labels: MergeNeeded, ReviewNeeded

#51 add1932, 2240
  README.md
  wjdgur778/JH_14501.cpp
  wjdgur778/JH_1725.cpp
  wjdgur778/JH_1918.cpp
  wjdgur778/JH_1932.cpp
  wjdgur778/JH_1966.cpp
  wjdgur778/JH_2096.cpp
  wjdgur778/JH_2164.cpp
  wjdgur778/JH_2240.cpp
  wjdgur778/JH_2304.cpp
  wjdgur778/JH_2841.cpp
  wjdgur778/JH_3078.cpp
  wjdgur778/JH_5430.cpp
  wjdgur778/NewBJ/NewBJ.sln
  wjdgur778/NewBJ/NewBJ.vcxproj
  wjdgur778/NewBJ/NewBJ.vcxproj.filters
  wjdgur778/NewBJ/NewBJ/JH_10026.cpp
  wjdgur778/NewBJ/NewBJ/JH_1051.cpp
  wjdgur778/NewBJ/NewBJ/JH_1107.cpp
  wjdgur778/NewBJ/NewBJ/JH_14717.cpp
  wjdgur778/NewBJ/NewBJ/JH_1541.cpp
  wjdgur778/NewBJ/NewBJ/JH_1707.cpp
  wjdgur778/NewBJ/NewBJ/JH_1946.cpp
  wjdgur778/NewBJ/NewBJ/JH_2875.cpp
  wjdgur778/NewBJ/NewBJ/JH_4179.cpp
  wjdgur778/NewBJ/NewBJ/NewBJ.vcxproj
  wjdgur778/NewBJ/NewBJ/NewBJ.vcxproj.filters
Labels: ReviewNeeded
