Repository sejong-algorithm/Algorithm, pull requests merged in 2019-07, with the labels that each got.

#3 Update README.md
  README.md
Labels: MergeNeeded

#5 함께하기 위한 커밋
  README.md
Labels: MergeNeeded

#22 나연이 추가
  README.md
Labels: MergeNeeded

#23 2 week
  KMinWoo/1725.cpp
  KMinWoo/1918.cpp
  KMinWoo/1966.cpp
  KMinWoo/2164.cpp
  KMinWoo/2304.cpp
  KMinWoo/2841.cpp
  KMinWoo/3078.cpp
  KMinWoo/5430.cpp
  KMinWoo/minwoo/minwoo.sln
  KMinWoo/minwoo/minwoo/1107.cpp
  KMinWoo/minwoo/minwoo/1541.cpp
  KMinWoo/minwoo/minwoo/minwoo.vcxproj
  KMinWoo/minwoo/minwoo/minwoo.vcxproj.filters
  README.md
Labels: URL ADD

#24 master problem url add
  README.md
Labels: URL ADD

#25 2 Week Merge Request
  README.md
  Zojae031/CodingTest/2304.cpp
  Zojae031/CodingTest/CodingTest.vcxproj
  Zojae031/CodingTest/CodingTest.vcxproj.filters
Labels: MergeNeeded

#26 2Week
  Zojae031/CodingTest/1725.cpp
  Zojae031/CodingTest/1918.cpp
  Zojae031/CodingTest/1966.cpp
  Zojae031/CodingTest/2164.cpp
  Zojae031/CodingTest/2841.cpp
  Zojae031/CodingTest/3078.cpp
  Zojae031/CodingTest/CodingTest.vcxproj
  Zojae031/CodingTest/CodingTest.vcxproj.filters
Labels: MergeNeeded

#29 2 week
  JeongMinGo/BJ1051.java
  JeongMinGo/BJ14717.java
  JeongMinGo/BJ1541.java
  JeongMinGo/BJ1946.java
  JeongMinGo/BJ2875.java
  Jung-jaeho/.DS_Store
  Jung-jaeho/1541.cpp
  Jung-jaeho/1918.cpp
  Jung-jaeho/1946.cpp
  Jung-jaeho/1966.cpp
  Jung-jaeho/2164.cpp
  Jung-jaeho/2841.cpp
  Jung-jaeho/2875.cpp
  KMinWoo/minwoo/minwoo/1051.cpp
  KMinWoo/minwoo/minwoo/14717.cpp
  KMinWoo/minwoo/minwoo/1946.cpp
  KMinWoo/minwoo/minwoo/2875.cpp
  README.md
  Zojae031/.DS_Store
  syli9526/BJ1051.cpp
  syli9526/BJ1107.cpp
  syli9526/BJ14717.cpp
  syli9526/BJ1541.cpp
  syli9526/BJ1946.cpp
  syli9526/BJ2875.cpp
  wjdgur778/NewBJ/NewBJ.sln
  wjdgur778/NewBJ/NewBJ/JH_1051.cpp
  wjdgur778/NewBJ/NewBJ/JH_1107.cpp
  wjdgur778/NewBJ/NewBJ/JH_14717.cpp
  wjdgur778/NewBJ/NewBJ/JH_1541.cpp
  wjdgur778/NewBJ/NewBJ/JH_1946.cpp
  wjdgur778/NewBJ/NewBJ/JH_2875.cpp
  wjdgur778/NewBJ/NewBJ/NewBJ.vcxproj
  wjdgur778/NewBJ/NewBJ/NewBJ.vcxproj.filters
Labels: MergeNeeded

#34 1 week
  README.md
Labels: MergeNeeded

#36 3week
  KMinWoo/10026.cpp
  KMinWoo/1707.cpp
  KMinWoo/1725.cpp
  KMinWoo/1918.cpp
  KMinWoo/1966.cpp
  KMinWoo/2164.cpp
  KMinWoo/2304.cpp
  KMinWoo/2841.cpp
  KMinWoo/3078.cpp
  KMinWoo/4179.cpp
  KMinWoo/5430.cpp
  KMinWoo/9372.cpp
  KMinWoo/minwoo/minwoo.sln
  KMinWoo/minwoo/minwoo/1051.cpp
  KMinWoo/minwoo/minwoo/1107.cpp
  KMinWoo/minwoo/minwoo/14717.cpp
  KMinWoo/minwoo/minwoo/1541.cpp
  KMinWoo/minwoo/minwoo/1946.cpp
  KMinWoo/minwoo/minwoo/2875.cpp
  KMinWoo/minwoo/minwoo/minwoo.vcxproj
  KMinWoo/minwoo/minwoo/minwoo.vcxproj.filters
  README.md
  Zojae031/CodingTest/1725.cpp
  Zojae031/CodingTest/1918.cpp
  Zojae031/CodingTest/1966.cpp
  Zojae031/CodingTest/2164.cpp
  Zojae031/CodingTest/2304.cpp
  Zojae031/CodingTest/2841.cpp
  Zojae031/CodingTest/3078.cpp
  Zojae031/CodingTest/CodingTest.vcxproj
  Zojae031/CodingTest/CodingTest.vcxproj.filters
  syli9526/BJ1725.cpp
  syli9526/BJ1918.cpp
  syli9526/BJ1966.cpp
  syli9526/BJ2164.cpp
  syli9526/BJ2304.cpp
  syli9526/BJ2841.cpp
  syli9526/BJ3078.cpp
  syli9526/BJ5430.cpp
Labels: URL ADD

#37 3 week A,B,C 코드
  README.md
  syli9526/BJ10026.cpp
  syli9526/BJ1051.cpp
  syli9526/BJ1107.cpp
  syli9526/BJ14717.cpp
  syli9526/BJ1541.cpp
  syli9526/BJ1707.cpp
  syli9526/BJ1725.cpp
  syli9526/BJ1918.cpp
  syli9526/BJ1946.cpp
  syli9526/BJ1966.cpp
  syli9526/BJ2164.cpp
  syli9526/BJ2304.cpp
  syli9526/BJ2841.cpp
  syli9526/BJ2875.cpp
  syli9526/BJ3078.cpp
  syli9526/BJ4179.cpp
  syli9526/BJ5430.cpp
  syli9526/BJ9372.cpp
Labels: ReviewNeeded

#38 10026 solve
  KMinWoo/10026.cpp
  KMinWoo/9372.cpp
Labels: URL ADD
